=== ihlys/book-catalog/src/test/resources/testdata/bookdaotest/dataset.dtd
<!ELEMENT dataset (Authors | Books | book_author)*>
<!ELEMENT Authors (#PCDATA)>
<!ELEMENT Books (#PCDATA)>
<!ELEMENT book_author (#PCDATA)>

<!ATTLIST Authors id CDATA #IMPLIED>
<!ATTLIST Authors forename CDATA #REQUIRED>
<!ATTLIST Authors surname CDATA #REQUIRED>

<!ATTLIST Books id CDATA #IMPLIED>
<!ATTLIST Books title CDATA #REQUIRED>
<!ATTLIST Books description CDATA #REQUIRED>
<!ATTLIST Books publicationDate CDATA #REQUIRED>

<!ATTLIST book_author book_id CDATA #REQUIRED>
<!ATTLIST book_author author_id CDATA #REQUIRED>

=== ihlys/book-catalog/src/test/resources/testdata/bookdaotest/data-source.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dataset SYSTEM "dataset.dtd">
<dataset>

	<Books id="1" title="Book one extra" 	 	description="This is book one"   publicationDate="1950-01-01"/>
	<Books id="2" title="Book two eeextraaaa" 	description="This is book two"   publicationDate="1950-01-01"/>
	<Books id="3" title="Book three ext ra" 	description="This is book three" publicationDate="1950-01-01"/>
	
	<Books id="4" title="Book four" description="This is book four" publicationDate="1950-01-01"/>
	
	<Books id="5" title="Book five" description="This is book five" publicationDate="1950-01-01"/>	
	<Authors id="1" forename="Author one forename" surname="Author one surname" />
	<book_author book_id="5" author_id="1" />

	<Authors id="2" forename="Author two forename"   surname="Author two surname" />
	<Authors id="3" forename="Author three forename" surname="Author three surname" />
	<Books id="6" title="Book six" description="This is book six" publicationDate="1950-01-01"/>
	<book_author book_id="6" author_id="2" />
	<book_author book_id="6" author_id="3" />
	
	
	<Books id="7" title="Book with many authors" description="This is with many authors" publicationDate="1950-01-01"/>
	<Authors id="4" forename="Co-author one forename"     surname="Co-author one surname" />
	<book_author book_id="7" author_id="4" />
	
	<Authors id="5" forename="Co-author two forename"     surname="Co-author two surname" />
	<Authors id="6" forename="Co-author three forename"   surname="Co-author three surname" />
	<Authors id="7" forename="Co-author four forename"    surname="Co-author four surname" />

	
</dataset>

=== ihlys/book-catalog/src/test/resources/testdata/authordaotest/data-source.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dataset SYSTEM "dataset.dtd">
<dataset>

	<Authors id="1" forename="Author one forename"   surname="Author one surname" />
	<Authors id="2" forename="Author two forename"   surname="Author two surname" />
	<Authors id="3" forename="Author three forename" surname="Author three surname" />
	
	<Books id="1" title="Book one"   description="This is book one"   publicationDate="1950-01-01"/>
	<Books id="2" title="Book two"   description="This is book two"   publicationDate="1950-01-01"/>
	<Books id="3" title="Book three" description="This is book three" publicationDate="1950-01-01"/>
	
	<book_author book_id="1" author_id="1" />
	<book_author book_id="2" author_id="1" />
	<book_author book_id="3" author_id="1" />
	
	<book_author book_id="1" author_id="2" />
	
	<Books id="4" title="Book four" description="This is book four" publicationDate="1950-01-01"/>
	<Books id="5" title="Book five" description="This is book five" publicationDate="1950-01-01"/>
	
	<book_author book_id="4" author_id="3" />	
	<book_author book_id="5" author_id="3" />	
	
</dataset>
